/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.13
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.xapian;

public class BB2Weight extends Weight {
  private transient long swigCPtr;

  protected BB2Weight(long cPtr, boolean cMemoryOwn) {
    super(XapianJNI.BB2Weight_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BB2Weight obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        XapianJNI.delete_BB2Weight(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public BB2Weight(double c) {
    this(XapianJNI.new_BB2Weight__SWIG_0(c), true);
  }

  public BB2Weight() {
    this(XapianJNI.new_BB2Weight__SWIG_1(), true);
  }

  public String name() {
    return XapianJNI.BB2Weight_name(swigCPtr, this);
  }

  public double getSumPart(long wdf, long doclen, long uniqterms) {
    return XapianJNI.BB2Weight_getSumPart(swigCPtr, this, wdf, doclen, uniqterms);
  }

  public double getMaxPart() {
    return XapianJNI.BB2Weight_getMaxPart(swigCPtr, this);
  }

  public double getSumExtra(long doclen, long uniqterms) {
    return XapianJNI.BB2Weight_getSumExtra(swigCPtr, this, doclen, uniqterms);
  }

  public double getMaxExtra() {
    return XapianJNI.BB2Weight_getMaxExtra(swigCPtr, this);
  }

}
