/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.13
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.xapian;

public class ESetIterator {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ESetIterator(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ESetIterator obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        XapianJNI.delete_ESetIterator(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setEset(ESet value) {
    XapianJNI.ESetIterator_eset_set(swigCPtr, this, ESet.getCPtr(value), value);
  }

  public ESet getEset() {
    long cPtr = XapianJNI.ESetIterator_eset_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ESet(cPtr, false);
  }

  public void setOff_from_end(long value) {
    XapianJNI.ESetIterator_off_from_end_set(swigCPtr, this, value);
  }

  public long getOff_from_end() {
    return XapianJNI.ESetIterator_off_from_end_get(swigCPtr, this);
  }

  public ESetIterator() {
    this(XapianJNI.new_ESetIterator(), true);
  }

  public double getWeight() {
    return XapianJNI.ESetIterator_getWeight(swigCPtr, this);
  }

  public String toString() {
    return XapianJNI.ESetIterator_toString(swigCPtr, this);
  }

  public String next() {
    return XapianJNI.ESetIterator_next(swigCPtr, this);
  }

  public boolean hasNext() {
    return XapianJNI.ESetIterator_hasNext(swigCPtr, this);
  }

  public boolean equals(ESetIterator o) {
    return XapianJNI.ESetIterator_equals(swigCPtr, this, ESetIterator.getCPtr(o), o);
  }

  public String getTerm() {
    return XapianJNI.ESetIterator_getTerm(swigCPtr, this);
  }

  public String prev() {
    return XapianJNI.ESetIterator_prev(swigCPtr, this);
  }

}
