/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.13
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.xapian;

public class LatLongDistanceKeyMaker extends KeyMaker {
  private transient long swigCPtr;

  protected LatLongDistanceKeyMaker(long cPtr, boolean cMemoryOwn) {
    super(XapianJNI.LatLongDistanceKeyMaker_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(LatLongDistanceKeyMaker obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        XapianJNI.delete_LatLongDistanceKeyMaker(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public LatLongDistanceKeyMaker(int slot_, LatLongCoords centre_, LatLongMetric metric_, double defdistance) {
    this(XapianJNI.new_LatLongDistanceKeyMaker__SWIG_0(slot_, LatLongCoords.getCPtr(centre_), centre_, LatLongMetric.getCPtr(metric_), metric_, defdistance), true);
  }

  public LatLongDistanceKeyMaker(int slot_, LatLongCoords centre_, LatLongMetric metric_) {
    this(XapianJNI.new_LatLongDistanceKeyMaker__SWIG_1(slot_, LatLongCoords.getCPtr(centre_), centre_, LatLongMetric.getCPtr(metric_), metric_), true);
  }

  public LatLongDistanceKeyMaker(int slot_, LatLongCoords centre_) {
    this(XapianJNI.new_LatLongDistanceKeyMaker__SWIG_2(slot_, LatLongCoords.getCPtr(centre_), centre_), true);
  }

  public LatLongDistanceKeyMaker(int slot_, LatLongCoord centre_, LatLongMetric metric_, double defdistance) {
    this(XapianJNI.new_LatLongDistanceKeyMaker__SWIG_3(slot_, LatLongCoord.getCPtr(centre_), centre_, LatLongMetric.getCPtr(metric_), metric_, defdistance), true);
  }

  public LatLongDistanceKeyMaker(int slot_, LatLongCoord centre_, LatLongMetric metric_) {
    this(XapianJNI.new_LatLongDistanceKeyMaker__SWIG_4(slot_, LatLongCoord.getCPtr(centre_), centre_, LatLongMetric.getCPtr(metric_), metric_), true);
  }

  public LatLongDistanceKeyMaker(int slot_, LatLongCoord centre_) {
    this(XapianJNI.new_LatLongDistanceKeyMaker__SWIG_5(slot_, LatLongCoord.getCPtr(centre_), centre_), true);
  }

  public String apply(Document doc) {
    return XapianJNI.LatLongDistanceKeyMaker_apply(swigCPtr, this, Document.getCPtr(doc), doc);
  }

}
