/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.13
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.xapian;

public class RangeProcessor {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected RangeProcessor(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(RangeProcessor obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        XapianJNI.delete_RangeProcessor(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    XapianJNI.RangeProcessor_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    XapianJNI.RangeProcessor_change_ownership(this, swigCPtr, true);
  }

  public RangeProcessor() {
    this(XapianJNI.new_RangeProcessor__SWIG_0(), true);
    XapianJNI.RangeProcessor_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

  public RangeProcessor(int slot_, String str_, long flags_) {
    this(XapianJNI.new_RangeProcessor__SWIG_1(slot_, str_, flags_), true);
    XapianJNI.RangeProcessor_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

  public RangeProcessor(int slot_, String str_) {
    this(XapianJNI.new_RangeProcessor__SWIG_2(slot_, str_), true);
    XapianJNI.RangeProcessor_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

  public RangeProcessor(int slot_) {
    this(XapianJNI.new_RangeProcessor__SWIG_3(slot_), true);
    XapianJNI.RangeProcessor_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

  public Query checkRange(String b, String e) {
    return new Query(XapianJNI.RangeProcessor_checkRange(swigCPtr, this, b, e), true);
  }

  public Query apply(String begin, String end) {
    return new Query((getClass() == RangeProcessor.class) ? XapianJNI.RangeProcessor_apply(swigCPtr, this, begin, end) : XapianJNI.RangeProcessor_applySwigExplicitRangeProcessor(swigCPtr, this, begin, end), true);
  }

  public RangeProcessor release() {
    long cPtr = XapianJNI.RangeProcessor_release(swigCPtr, this);
    return (cPtr == 0) ? null : new RangeProcessor(cPtr, false);
  }

}
