/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.13
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.xapian;

public class Registry {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Registry(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Registry obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        XapianJNI.delete_Registry(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Registry() {
    this(XapianJNI.new_Registry(), true);
  }

  public void registerWeightingScheme(Weight wt) {
    XapianJNI.Registry_registerWeightingScheme(swigCPtr, this, Weight.getCPtr(wt), wt);
  }

  public Weight getWeightingScheme(String name) {
    long cPtr = XapianJNI.Registry_getWeightingScheme(swigCPtr, this, name);
    return (cPtr == 0) ? null : new Weight(cPtr, false);
  }

  public void registerPostingSource(PostingSource source) {
    XapianJNI.Registry_registerPostingSource(swigCPtr, this, PostingSource.getCPtr(source), source);
  }

  public PostingSource getPostingSource(String name) {
    long cPtr = XapianJNI.Registry_getPostingSource(swigCPtr, this, name);
    return (cPtr == 0) ? null : new PostingSource(cPtr, false);
  }

  public void registerMatchSpy(MatchSpy spy) {
    XapianJNI.Registry_registerMatchSpy(swigCPtr, this, MatchSpy.getCPtr(spy), spy);
  }

  public MatchSpy getMatchSpy(String name) {
    long cPtr = XapianJNI.Registry_getMatchSpy(swigCPtr, this, name);
    return (cPtr == 0) ? null : new MatchSpy(cPtr, false);
  }

  public void registerLatLongMetric(LatLongMetric metric) {
    XapianJNI.Registry_registerLatLongMetric(swigCPtr, this, LatLongMetric.getCPtr(metric), metric);
  }

  public LatLongMetric getLatLongMetric(String name) {
    long cPtr = XapianJNI.Registry_getLatLongMetric(swigCPtr, this, name);
    return (cPtr == 0) ? null : new LatLongMetric(cPtr, false);
  }

}
