/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.13
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.xapian;

public class ValuePostingSource extends PostingSource {
  private transient long swigCPtr;

  protected ValuePostingSource(long cPtr, boolean cMemoryOwn) {
    super(XapianJNI.ValuePostingSource_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ValuePostingSource obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        XapianJNI.delete_ValuePostingSource(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    XapianJNI.ValuePostingSource_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    XapianJNI.ValuePostingSource_change_ownership(this, swigCPtr, true);
  }

  public ValuePostingSource(int slot_) {
    this(XapianJNI.new_ValuePostingSource(slot_), true);
    XapianJNI.ValuePostingSource_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

  public long getTermfreqMin() {
    return (getClass() == ValuePostingSource.class) ? XapianJNI.ValuePostingSource_getTermfreqMin(swigCPtr, this) : XapianJNI.ValuePostingSource_getTermfreqMinSwigExplicitValuePostingSource(swigCPtr, this);
  }

  public long getTermfreqEst() {
    return (getClass() == ValuePostingSource.class) ? XapianJNI.ValuePostingSource_getTermfreqEst(swigCPtr, this) : XapianJNI.ValuePostingSource_getTermfreqEstSwigExplicitValuePostingSource(swigCPtr, this);
  }

  public long getTermfreqMax() {
    return (getClass() == ValuePostingSource.class) ? XapianJNI.ValuePostingSource_getTermfreqMax(swigCPtr, this) : XapianJNI.ValuePostingSource_getTermfreqMaxSwigExplicitValuePostingSource(swigCPtr, this);
  }

  public void next(double min_wt) {
    if (getClass() == ValuePostingSource.class) XapianJNI.ValuePostingSource_next(swigCPtr, this, min_wt); else XapianJNI.ValuePostingSource_nextSwigExplicitValuePostingSource(swigCPtr, this, min_wt);
  }

  public void skipTo(long min_docid, double min_wt) {
    if (getClass() == ValuePostingSource.class) XapianJNI.ValuePostingSource_skipTo(swigCPtr, this, min_docid, min_wt); else XapianJNI.ValuePostingSource_skipToSwigExplicitValuePostingSource(swigCPtr, this, min_docid, min_wt);
  }

  public boolean check(long min_docid, double min_wt) {
    return (getClass() == ValuePostingSource.class) ? XapianJNI.ValuePostingSource_check(swigCPtr, this, min_docid, min_wt) : XapianJNI.ValuePostingSource_checkSwigExplicitValuePostingSource(swigCPtr, this, min_docid, min_wt);
  }

  public boolean atEnd() {
    return (getClass() == ValuePostingSource.class) ? XapianJNI.ValuePostingSource_atEnd(swigCPtr, this) : XapianJNI.ValuePostingSource_atEndSwigExplicitValuePostingSource(swigCPtr, this);
  }

  public long getDocId() {
    return (getClass() == ValuePostingSource.class) ? XapianJNI.ValuePostingSource_getDocId(swigCPtr, this) : XapianJNI.ValuePostingSource_getDocIdSwigExplicitValuePostingSource(swigCPtr, this);
  }

  public void init(Database db_) {
    if (getClass() == ValuePostingSource.class) XapianJNI.ValuePostingSource_init(swigCPtr, this, Database.getCPtr(db_), db_); else XapianJNI.ValuePostingSource_initSwigExplicitValuePostingSource(swigCPtr, this, Database.getCPtr(db_), db_);
  }

  public Database getDatabase() {
    return new Database(XapianJNI.ValuePostingSource_getDatabase(swigCPtr, this), true);
  }

  public int getSlot() {
    return XapianJNI.ValuePostingSource_getSlot(swigCPtr, this);
  }

  public byte[] getValue() {
    return XapianJNI.ValuePostingSource_getValue(swigCPtr, this);
  }

  public void done() {
    XapianJNI.ValuePostingSource_done(swigCPtr, this);
  }

  public boolean getStarted() {
    return XapianJNI.ValuePostingSource_getStarted(swigCPtr, this);
  }

  public void setTermfreqMin(long termfreq_min_) {
    XapianJNI.ValuePostingSource_setTermfreqMin(swigCPtr, this, termfreq_min_);
  }

  public void setTermfreqEst(long termfreq_est_) {
    XapianJNI.ValuePostingSource_setTermfreqEst(swigCPtr, this, termfreq_est_);
  }

  public void setTermfreqMax(long termfreq_max_) {
    XapianJNI.ValuePostingSource_setTermfreqMax(swigCPtr, this, termfreq_max_);
  }

}
