/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.13
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.xapian;

public interface XapianConstants {
  public final static int BAD_VALUENO = XapianJNI.BAD_VALUENO_get();
  public final static int DB_CREATE = XapianJNI.DB_CREATE_get();
  public final static int DB_CREATE_OR_OPEN = XapianJNI.DB_CREATE_OR_OPEN_get();
  public final static int DB_CREATE_OR_OVERWRITE = XapianJNI.DB_CREATE_OR_OVERWRITE_get();
  public final static int DB_OPEN = XapianJNI.DB_OPEN_get();
  public final static int DB_NO_SYNC = XapianJNI.DB_NO_SYNC_get();
  public final static int DB_FULL_SYNC = XapianJNI.DB_FULL_SYNC_get();
  public final static int DB_DANGEROUS = XapianJNI.DB_DANGEROUS_get();
  public final static int DB_NO_TERMLIST = XapianJNI.DB_NO_TERMLIST_get();
  public final static int DB_BACKEND_CHERT = XapianJNI.DB_BACKEND_CHERT_get();
  public final static int DB_BACKEND_GLASS = XapianJNI.DB_BACKEND_GLASS_get();
  public final static int DB_BACKEND_INMEMORY = XapianJNI.DB_BACKEND_INMEMORY_get();
  public final static int DB_BACKEND_STUB = XapianJNI.DB_BACKEND_STUB_get();
  public final static int DB_RETRY_LOCK = XapianJNI.DB_RETRY_LOCK_get();
  public final static int DBCHECK_SHORT_TREE = XapianJNI.DBCHECK_SHORT_TREE_get();
  public final static int DBCHECK_FULL_TREE = XapianJNI.DBCHECK_FULL_TREE_get();
  public final static int DBCHECK_SHOW_FREELIST = XapianJNI.DBCHECK_SHOW_FREELIST_get();
  public final static int DBCHECK_SHOW_STATS = XapianJNI.DBCHECK_SHOW_STATS_get();
  public final static int DBCHECK_FIX = XapianJNI.DBCHECK_FIX_get();
  public final static int DBCOMPACT_MULTIPASS = XapianJNI.DBCOMPACT_MULTIPASS_get();
  public final static int DBCOMPACT_NO_RENUMBER = XapianJNI.DBCOMPACT_NO_RENUMBER_get();
  public final static int DBCOMPACT_SINGLE_FILE = XapianJNI.DBCOMPACT_SINGLE_FILE_get();
  public final static int DOC_ASSUME_VALID = XapianJNI.DOC_ASSUME_VALID_get();
  public final static int RP_SUFFIX = XapianJNI.RP_SUFFIX_get();
  public final static int RP_REPEATED = XapianJNI.RP_REPEATED_get();
  public final static int RP_DATE_PREFER_MDY = XapianJNI.RP_DATE_PREFER_MDY_get();

}
