/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.13
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.xapian;

public class Xapian implements XapianConstants {
  public static byte[] sortableSerialise(double value) {
    return XapianJNI.sortableSerialise(value);
  }

  public static double sortableUnserialise(byte[] serialised) {
    return XapianJNI.sortableUnserialise(serialised);
  }

  public static double milesToMetres(double miles) {
    return XapianJNI.milesToMetres(miles);
  }

  public static double metresToMiles(double metres) {
    return XapianJNI.metresToMiles(metres);
  }

  public static int getBAD_VALUENO() {
    return XapianJNI.getBAD_VALUENO();
  }

}
