//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.13
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Xapian {

public class LatLongDistancePostingSource : ValuePostingSource {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal LatLongDistancePostingSource(global::System.IntPtr cPtr, bool cMemoryOwn) : base(XapianPINVOKE.LatLongDistancePostingSource_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(LatLongDistancePostingSource obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~LatLongDistancePostingSource() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          XapianPINVOKE.delete_LatLongDistancePostingSource(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public LatLongDistancePostingSource(uint slot_, LatLongCoords centre_, LatLongMetric metric_, double max_range_, double k1_, double k2_) : this(XapianPINVOKE.new_LatLongDistancePostingSource__SWIG_0(slot_, LatLongCoords.getCPtr(centre_), LatLongMetric.getCPtr(metric_), max_range_, k1_, k2_), true) {
    if (XapianPINVOKE.SWIGPendingException.Pending) throw XapianPINVOKE.SWIGPendingException.Retrieve();
  }

  public LatLongDistancePostingSource(uint slot_, LatLongCoords centre_, LatLongMetric metric_, double max_range_, double k1_) : this(XapianPINVOKE.new_LatLongDistancePostingSource__SWIG_1(slot_, LatLongCoords.getCPtr(centre_), LatLongMetric.getCPtr(metric_), max_range_, k1_), true) {
    if (XapianPINVOKE.SWIGPendingException.Pending) throw XapianPINVOKE.SWIGPendingException.Retrieve();
  }

  public LatLongDistancePostingSource(uint slot_, LatLongCoords centre_, LatLongMetric metric_, double max_range_) : this(XapianPINVOKE.new_LatLongDistancePostingSource__SWIG_2(slot_, LatLongCoords.getCPtr(centre_), LatLongMetric.getCPtr(metric_), max_range_), true) {
    if (XapianPINVOKE.SWIGPendingException.Pending) throw XapianPINVOKE.SWIGPendingException.Retrieve();
  }

  public LatLongDistancePostingSource(uint slot_, LatLongCoords centre_, LatLongMetric metric_) : this(XapianPINVOKE.new_LatLongDistancePostingSource__SWIG_3(slot_, LatLongCoords.getCPtr(centre_), LatLongMetric.getCPtr(metric_)), true) {
    if (XapianPINVOKE.SWIGPendingException.Pending) throw XapianPINVOKE.SWIGPendingException.Retrieve();
  }

  public LatLongDistancePostingSource(uint slot_, LatLongCoords centre_, double max_range_, double k1_, double k2_) : this(XapianPINVOKE.new_LatLongDistancePostingSource__SWIG_4(slot_, LatLongCoords.getCPtr(centre_), max_range_, k1_, k2_), true) {
    if (XapianPINVOKE.SWIGPendingException.Pending) throw XapianPINVOKE.SWIGPendingException.Retrieve();
  }

  public LatLongDistancePostingSource(uint slot_, LatLongCoords centre_, double max_range_, double k1_) : this(XapianPINVOKE.new_LatLongDistancePostingSource__SWIG_5(slot_, LatLongCoords.getCPtr(centre_), max_range_, k1_), true) {
    if (XapianPINVOKE.SWIGPendingException.Pending) throw XapianPINVOKE.SWIGPendingException.Retrieve();
  }

  public LatLongDistancePostingSource(uint slot_, LatLongCoords centre_, double max_range_) : this(XapianPINVOKE.new_LatLongDistancePostingSource__SWIG_6(slot_, LatLongCoords.getCPtr(centre_), max_range_), true) {
    if (XapianPINVOKE.SWIGPendingException.Pending) throw XapianPINVOKE.SWIGPendingException.Retrieve();
  }

  public LatLongDistancePostingSource(uint slot_, LatLongCoords centre_) : this(XapianPINVOKE.new_LatLongDistancePostingSource__SWIG_7(slot_, LatLongCoords.getCPtr(centre_)), true) {
    if (XapianPINVOKE.SWIGPendingException.Pending) throw XapianPINVOKE.SWIGPendingException.Retrieve();
  }

  public override void Next(double min_wt) {
    XapianPINVOKE.LatLongDistancePostingSource_Next(swigCPtr, min_wt);
    if (XapianPINVOKE.SWIGPendingException.Pending) throw XapianPINVOKE.SWIGPendingException.Retrieve();
  }

  public override void SkipTo(uint min_docid, double min_wt) {
    XapianPINVOKE.LatLongDistancePostingSource_SkipTo(swigCPtr, min_docid, min_wt);
    if (XapianPINVOKE.SWIGPendingException.Pending) throw XapianPINVOKE.SWIGPendingException.Retrieve();
  }

  public override bool Check(uint min_docid, double min_wt) {
    bool ret = XapianPINVOKE.LatLongDistancePostingSource_Check(swigCPtr, min_docid, min_wt);
    if (XapianPINVOKE.SWIGPendingException.Pending) throw XapianPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override double GetWeight() {
    double ret = XapianPINVOKE.LatLongDistancePostingSource_GetWeight(swigCPtr);
    if (XapianPINVOKE.SWIGPendingException.Pending) throw XapianPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override string Name() {
    string ret = XapianPINVOKE.LatLongDistancePostingSource_Name(swigCPtr);
    if (XapianPINVOKE.SWIGPendingException.Pending) throw XapianPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override void Init(Database db_) {
    XapianPINVOKE.LatLongDistancePostingSource_Init(swigCPtr, Database.getCPtr(db_));
    if (XapianPINVOKE.SWIGPendingException.Pending) throw XapianPINVOKE.SWIGPendingException.Retrieve();
  }

  public override string GetDescription() {
    string ret = XapianPINVOKE.LatLongDistancePostingSource_GetDescription(swigCPtr);
    if (XapianPINVOKE.SWIGPendingException.Pending) throw XapianPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}

}
